### ISSUE TITLE
chore: Confirm Flutter 3.24.0 and Dart 3.5 Support

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/flame_behaviors#63]
**Description**

With the release of Flutter 3.24.0 and Dart 3.5 some things are breaking. Need to review the package and make any necessary fixes.

**Requirements**

- [ ] Package works correctly on Flutter 3.24.0 and Dart 3.5
- [ ] We prepare and release a new version to be released

**Comment by tomarra** [comment]
Moving this back to "Todo" in order to create a new release with the changes.

**Comment by alestiago** [comment]
#65 prepares some workflows for automatically releasing.

**Comment by tomarra** [comment]
This is all released and automated now so closing this out as completed.
